INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');

INSERT IGNORE INTO market_actions(name) VALUES('BYU');
INSERT IGNORE INTO market_actions(name) VALUES('SELL');
INSERT IGNORE INTO market_actions(name) VALUES('COUPON');
INSERT IGNORE INTO market_actions(name) VALUES('AMORTIZATION');
INSERT IGNORE INTO market_actions(name) VALUES('DIVIDEND');
INSERT IGNORE INTO market_actions(name) VALUES('DEPOSIT');
INSERT IGNORE INTO market_actions(name) VALUES('WITHDRAW');
INSERT IGNORE INTO market_actions(name) VALUES('INCOME');
INSERT IGNORE INTO market_actions(name) VALUES('LOSS');

INSERT IGNORE INTO markets(name) VALUES('NYSE');
INSERT IGNORE INTO markets(name) VALUES('MOEX');